### ISSUE TITLE
Working with sparkfun amp MAX31855K and Raspberry Pi Zero 2W

### ISSUE THREAD

**Issue by gabrielDiaz-performlab** [gregorychen3/espresso-controller#33]
Not so much an issue as much as information for those in a similar position. 

I was curious to switch from https://github.com/brycesub/silvia-pi/ to this package, and my first attempt was with the silvia-pi hardware.  This involves a different amp than the one suggested by this module.  

I am also using a Pi Zero 2w.  This is a multiprocessor unit, and I hope it overcomes the limitations Gregory points out in his readme.

https://www.sparkfun.com/products/13266
It is still running on the MAX31855K, so I was hopeful for a simple swapout.

At first, I was getting the error: "Failed to sample temperature	{"error": "short to ground"}"

I changed two things at the same time and the issue was resolved.

1) I switched the USB power source from my computer to the same wall outlet that was charging the Silvia
2) I plugged the free-floating "NC" line running from the thermocouple into a ground slot on the PI.

Perhaps obvious things to those who are a bit more experience, but neither seemed obvious to me.  

I'm looking forward to tomorrow morning's shot.  Thanks again, Greg!

**Comment by gabrielDiaz-performlab** [comment]
The grounding issue popped up again when I had an monitor plugged in through HMDI and a keyboard through USB.  Removing them and SSHing in resolved the issue.

**Comment by gregorychen3** [comment]
Hi @gabrielDiaz-performlab , that error is telling your that your thermocouple wiring is short-circuiting somewhere. I'd recommend checking how you are securing your thermocouple tip to the boiler.

When working on this project, I also noticed that improper installation of the thermocouple tip (e.g., damaged insulation around the tip due to pinching the tip too hard with a metal fastener) could trigger this error. **Make sure that the 2 ends of the thermocouple tip are not connected anywhere other than the "hot junction".** If you are using some sort of conductive metal fastener to secure the tip to the boiler, be sure to wrap the tip in some insulator, like scotch tape, first. This [thermocouple](https://www.amazon.com/gp/product/B01NBM7SBK) is anb example of a good quality one that comes with a pre-insulated tip.

If none of the above helps, you may have from a bad MAX31855 or thermocouple. I highly doubt that your error is due to your usb/hdmi/power connections.

**Comment by gabrielDiaz-performlab** [comment]
Just a heads up that I did end up getting this working, despite noise that I cannot seem to account for.  Thank you very much for your hard work!  After manually tuning my controller, I have the Silvia up to target temp in about 5 mins, with only a minor overshoot and recovery.  It is also very quick to return to temp after a shot has been pulled.  Ideal.  Beautiful.  Delicious.

**Comment by gregorychen3** [comment]
fantastic!
